module.exports =  {
		'Top Stories': ' 🤙',
		'World': ' 🌍',
		'UK': ' 🇬🇧',
		'England': '',
		'NorthernIreland': '',
		'Scotland': '',
		'Wales': '',
		'Business': ' 🤝',
		'Politics': ' 🏛',
		'Health': ' 🚑',
		'Education': ' 👩‍🏫',
		'Science': ' 🔬',
		'Technology': ' 📱',
		'Entertainment': ' 🎞',
		'HaveYourSay': ' ✋',
		'Gossip': ' 💑',
		'Sport': ' 🏆',
		'Football':' ⚽',
		'Tennis': ' 🎾',
		'Cricket': ' 🏏',
		'Golf': ' ⛳',
		'Snooker': ' 🎱',
		'Rugby Union': ' 🏉',
		'Rugby League': ' 🏉',
		'England': '',
		'Northern Ireland': '',
		'Scotland': '',
		'Wales': '',
		'Africa': '',
		'Asia': '',
		'China': ' 🇨🇳',
		'India': ' 🇮🇳',
		'Australia': ' 🇦🇺',
		'Europe': ' 🇪🇺',
		'Latin America': '',
		'Middle East': '',
		'US And Canada': ' 🇺🇸🇨🇦',
	}