module.exports =  {
		'Top Stories': ' 🤙',
		'World': ' 🌍',
		'UK': ' 🇬🇧',
		'England': '',
		'NorthernIreland': '',
		'Scotland': '',
		'Wales': '',
		'Business': ' 🤝',
		'Politics': ' 🏛',
		'Health': ' 🚑',
		'Education': ' 👩‍🏫',
		'Science': ' 🔬',
		'Technology': ' 📱',
		'Entertainment': ' 🎞',
		'HaveYourSay': ' ✋',
		'Gossip': ' 💑',
		'Sport': ' ⚽',
	}